version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet --version
build_script:
- cmd: dotnet build --configuration Release
test:
  assemblies:
    - '**\*Tests.dll'
artifacts:
- path: nugets\**\*.nupkg